# TP NUMPY

In [23]:
import numpy as np

## Question 2

In [24]:
array1 = np.array([5, 10, 15, 20, 25])
print("array1:", array1)

array2 = np.zeros((4, 4))
print("array2:\n", array2)

array3 = np.ones((3, 2))
print("array3:\n", array3)

array4 = np.arange(0, 20, 3)
print("array4:", array4)

array1: [ 5 10 15 20 25]
array2:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
array3:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]
array4: [ 0  3  6  9 12 15 18]


## Question 3

In [25]:
array1_reshaped = array1.reshape(5, 1)
print("array1_reshaped:\n", array1_reshaped)

array2_flattened = array2.flatten()
print("array2_flattened:", array2_flattened)

array_concat = np.concatenate((array1, array4))
print("array_concat:", array_concat)

array1_reshaped:
 [[ 5]
 [10]
 [15]
 [20]
 [25]]
array2_flattened: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
array_concat: [ 5 10 15 20 25  0  3  6  9 12 15 18]


## Question 4

In [26]:
sum_array3 = np.sum(array3)
print("Somme array3:", sum_array3)

mean_array4 = np.mean(array4)
print("Moyenne array4:", mean_array4)

max_array1 = np.max(array1)
print("Valeur maximale array1:", max_array1)

min_array4 = np.min(array4)
print("Valeur minimale array4:", min_array4)

std_array2 = np.std(array2)
print("Écart-type array2:", std_array2)

Somme array3: 6.0
Moyenne array4: 9.0
Valeur maximale array1: 25
Valeur minimale array4: 0
Écart-type array2: 0.0


## Question 5

In [27]:
element = array2[1, 2] 
print("Élément [1, 2] array2:", element)

col2 = array3[:, 1]
print("2ème colonne de array3:", col2)

rows = array2[1:4, :]
print("Lignes 1 à 3 de array2:\n", rows)

Élément [1, 2] array2: 0.0
2ème colonne de array3: [1. 1. 1.]
Lignes 1 à 3 de array2:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


## Question 6

In [28]:
matrix1 = np.random.random((2, 2))
matrix2 = np.random.random((2, 2))
print("matrix1:\n", matrix1)
print("matrix2:\n", matrix2)

matrix_product = np.matmul(matrix1, matrix2)
print("Produit matriciel:\n", matrix_product)

matrix1_inverse = np.linalg.inv(matrix1)
print("Inverse matrix1:\n", matrix1_inverse)

matrix2_det = np.linalg.det(matrix2)
print("Déterminant matrix2:", matrix2_det)

matrix1:
 [[0.67382956 0.75685565]
 [0.20903899 0.03976445]]
matrix2:
 [[0.15564971 0.95152185]
 [0.03306196 0.66253134]]
Produit matriciel:
 [[0.12990451 1.14260413]
 [0.03385155 0.22525036]]
Inverse matrix1:
 [[-0.30258025  5.75915306]
 [ 1.59064349 -5.12738134]]
Déterminant matrix2: 0.07166363459621264


## Question 7

In [29]:
random_array1 = np.random.random((3, 3))
print("random_array1:\n", random_array1)

random_array2 = np.random.randint(0, 11, (2, 2))
print("random_array2:\n", random_array2)

random_array1:
 [[0.73079734 0.58193141 0.75920257]
 [0.98231359 0.67761212 0.51938603]
 [0.19153367 0.82666778 0.08844049]]
random_array2:
 [[0 6]
 [1 3]]


## Question 8

In [30]:
np.save('array1.npy', array1)

loaded_array = np.load('array1.npy')
print("loaded_array:", loaded_array)

loaded_array: [ 5 10 15 20 25]


## Question 9

In [34]:
X = np.random.random((100, 5))

y = np.random.randint(0, 2, 100)

X_normalized = (X - np.mean(X, axis=0)) / np.std(X, axis=0)
print("Mean after normalization:", np.mean(X_normalized, axis=0))
print("Std after normalization:", np.std(X_normalized, axis=0))

cov_matrix = np.cov(X.T)
print("Covariance matrix:\n", cov_matrix)

Mean after normalization: [ 4.77395901e-16  1.23456800e-15  5.86197757e-16 -1.93178806e-16
 -5.95079541e-16]
Std after normalization: [1. 1. 1. 1. 1.]
Covariance matrix:
 [[ 0.07672017 -0.01072052  0.00019208  0.0038929   0.00414168]
 [-0.01072052  0.08367872  0.00350238 -0.01318844 -0.00994572]
 [ 0.00019208  0.00350238  0.07891806  0.0034477   0.00131597]
 [ 0.0038929  -0.01318844  0.0034477   0.08237074 -0.00558261]
 [ 0.00414168 -0.00994572  0.00131597 -0.00558261  0.08499516]]
